"""The desk sequence, manual navigation and lazy page fetching."""
from browser_helpers import browser_page
from playwright.sync_api import expect


with browser_page('/') as page:
    reader = page.locator('#manual')
    expect(page.locator('#box')).to_be_visible()
    expect(reader).to_be_hidden()
    tabs = page.get_by_role('navigation', name='Desk')
    expect(tabs).to_be_hidden()
    page.get_by_role('button', name='Turn the box over').click()
    expect(page.locator('#box')).to_be_hidden()
    page.get_by_role('button', name='Open the box').click()
    expect(tabs).to_be_visible()
    page.get_by_role('button', name='Read the manual').click()
    expect(reader).to_be_visible()
    image = reader.locator('img')
    previous = reader.get_by_role('button', name='Previous manual page')
    next_page = reader.get_by_role('button', name='Next manual page')
    select = reader.get_by_role('combobox', name='Manual scan')
    requests = []
    page.on('request', lambda request: requests.append(request.url)
            if '/assets/manual/' in request.url else None)
    expect(previous).to_be_disabled()
    expect(select.locator('option')).to_have_count(20)
    next_page.click()
    expect(image).to_have_attribute('src', '/assets/manual/02.webp')
    expect(previous).to_be_enabled()
    select.select_option('20')
    expect(next_page).to_be_disabled()
    expect(image).to_have_attribute('alt', 'Original Below the Root manual, scan 20 of 20')
    previous.click()
    expect(select).to_have_value('19')
    expect(next_page).to_be_enabled()
    select.select_option('5')
    next_page.focus()
    page.keyboard.press('Space')
    expect(select).to_have_value('6')
    select.focus()
    page.keyboard.press('m')
    expect(page.locator('#map-screen')).to_be_hidden()
    assert not any(url.endswith('/10.webp') for url in requests), requests
    reader.get_by_role('link', name='Turn the page').click()
    expect(select).to_have_value('7')
    tabs.get_by_role('button', name='Map').click()
    expect(reader).to_be_hidden()
    expect(page.locator('#paper-map')).to_be_visible()
    tabs.get_by_role('button', name='Box').click()
    expect(page.locator('#box-open')).to_be_visible()
    page.get_by_role('button', name='Close the box').click()
    expect(page.locator('#box')).to_be_visible()
    expect(tabs).to_be_hidden()

with browser_page('/') as page:
    page.get_by_role('button', name='Turn the box over').click()
    page.get_by_role('button', name='Open the box').click()
    power = page.locator('#monitor-power')
    expect(power).to_have_attribute('aria-pressed', 'false')
    expect(page.locator('#play')).to_be_hidden()
    page.get_by_role('button', name='Put the disk in the computer').click()
    expect(power).to_have_attribute('aria-pressed', 'true')
    expect(page.locator('#screen')).to_be_focused()

print('pass: desk sequence, desk tabs, disk power-on, manual navigation and on-demand scans')
