import assert from 'node:assert/strict';
import { createHandler } from '../functions/github.mjs';
const origin = 'https://below-the-root.netlify.app';
const base = origin + '/.netlify/functions/github';
const env = { GITHUB_CLIENT_ID: 'test-client', GITHUB_CLIENT_SECRET: 'test-secret', GITHUB_SESSION_SECRET: 'a'.repeat(32) };
let calls = [];
let reject = false;
const remote = async (url, options) => {
  calls.push({ url, options });
  if (url.endsWith('/access_token')) return Response.json({ access_token: 'private-test-token' });
  if (url.endsWith('/user')) return Response.json({ login: 'tester' });
  if (reject) return Response.json({}, { status: 403 });
  return Response.json({ html_url: 'https://github.com/century-arcade/below-the-root/issues/123', number: 123 });
};
const handler = createHandler(env, remote);
const req = (op, headers = {}, body) => new Request(base + '?op=' + op, { method: body ? 'POST' : 'GET', headers, body });
assert.equal((await (await createHandler({})(req('session'))).json()).configured, false);
const login = await handler(req('login'));
assert.equal(login.status, 302);
const auth = new URL(login.headers.get('Location'));
assert.equal(auth.origin, 'https://github.com');
assert.equal(auth.searchParams.get('code_challenge_method'), 'S256');
const flowCookie = login.headers.getSetCookie()[0].split(';')[0];
assert.match(login.headers.getSetCookie()[0], /Secure; HttpOnly; SameSite=Lax/);
const bad = await handler(req('callback&state=bad&code=test', { Cookie: flowCookie }));
assert.match(bad.headers.get('Location'), /failed/); assert.equal(calls.length, 0);
const callback = await handler(req('callback&code=test&state=' + auth.searchParams.get('state'), { Cookie: flowCookie }));
assert.equal(callback.headers.get('Location'), '/?debug');
const sessionCookie = callback.headers.getSetCookie().find(x => x.startsWith('__Host-btr-github=')).split(';')[0];
assert.ok(!sessionCookie.includes('private-test-token'));
const info = await handler(req('session', { Cookie: sessionCookie }));
assert.deepEqual(await info.json(), { configured: true, login: 'tester' });
const headers = { Cookie: sessionCookie, Origin: origin, 'Content-Type': 'application/json' };
const body = JSON.stringify({ message: 'Door failed\nI tapped it.', context: 'Room T1' });
assert.equal((await handler(req('issue', { ...headers, Origin: 'https://other.example' }, body))).status, 403);
assert.equal((await handler(req('issue', { Origin: origin, 'Content-Type': 'application/json' }, body))).status, 401);
assert.equal((await handler(req('issue', headers, JSON.stringify({ message: '', context: '' })))).status, 400);
const result = await handler(req('issue', headers, body));
assert.equal((await result.json()).number, 123);
const sent = calls.at(-1);
assert.equal(sent.url, 'https://api.github.com/repos/century-arcade/below-the-root/issues');
assert.deepEqual(JSON.parse(sent.options.body), { title: 'Door failed', body: 'Door failed\nI tapped it.\n\nRoom T1' });
reject = true;
assert.equal((await handler(req('issue', headers, body))).status, 502);
const logout = await handler(req('logout', headers, '{}'));
assert.match(logout.headers.get('Set-Cookie'), /Max-Age=0/);
console.log('github_test: OAuth PKCE, state rejection, encrypted cookie, CSRF, fixed repository, issue creation and error handling passed (mock GitHub)');
