import { test } from 'node:test';
import assert from 'node:assert/strict';
import { statusRows } from '../src/status.js';
import { clearPanel, say } from '../src/panel.js';
import { statusLayout } from '../src/video.js';
import { give, loadTestData } from './helpers.js';
import { newState, startQuest } from '../src/game.js';
import { IDLE } from '../src/input.js';
import { CLASS } from '../src/data.js';

test('messages and menus own the shared text panel while permanent status remains visible', async () => {
  const data = await loadTestData();
  const state = newState(data, { read: () => IDLE });
  startQuest(state, data.characters[0]);
  give(state, CLASS.BREAD);
  const inventoryRows = statusRows(state).slice(0, -2);
  let layout = statusLayout(state, statusRows(state));
  assert.deepEqual(layout.panelRows, inventoryRows, 'inventory occupies the game text panel');
  say(state, 'A MESSAGE');
  layout = statusLayout(state, statusRows(state));
  assert.deepEqual(layout.panelRows, [], 'a message owns the text panel');
  assert.deepEqual(layout.bandRows.slice(-2), statusRows(state).slice(-2), 'permanent status stays in its bottom rows');
  clearPanel(state);
  assert.deepEqual(statusLayout(state, statusRows(state)).panelRows, inventoryRows, 'inventory returns when the message clears');
  state.commandMenuOpen = true;
  assert.deepEqual(statusLayout(state, statusRows(state)).panelRows, [], 'the menu owns the panel before its first text is drawn');
  assert.deepEqual(statusLayout(state, statusRows(state)).bandRows, layout.bandRows, 'switching to the menu preserves status');
  state.commandMenuOpen = false;
  const playback = { roomChanges: 1, totalRoomChanges: 3 };
  const classicLayout = statusLayout(state, statusRows(state, { classic: true, playback }), { classic: true });
  assert.deepEqual(classicLayout.panelRows, ['1/3'], 'classic replay details belong to the shared panel');
  assert.ok(classicLayout.bandRows.every(row => row === ''), 'classic mode leaves permanent status empty');
});
