[build]
command = "make build"
publish = "_build"

[functions]
directory = "functions"

[dev]
framework = "#static"
publish = "_build"
port = 8000
autoLaunch = false

[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/play"
to = "/play.html"
status = 200

[[redirects]]
from = "/resources"
to = "/resources.html"
status = 200
